#!/usr/bin/env python3
"""Advance canonical ENA control-plane pointers after candidate.1 exact freeze.

Exact-anchor transformation only. Candidate cargo and Current are out of scope.
"""
from pathlib import Path


def apply(path: str, replacements: list[tuple[str, str]]) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    for old, new in replacements:
        count = text.count(old)
        if count != 1:
            raise SystemExit(f"{path}: expected one anchor, found {count}: {old!r}")
        text = text.replace(old, new, 1)
    p.write_text(text, encoding="utf-8")


apply("research/ACTIVE-RESEARCH.yaml", [
    ('  state: "V0_3_7_CANDIDATE1_SUCCESSOR_REPAIR_RECONCILED / EXACT_PREFREEZE_NEXT / NOT_FROZEN / NOT_CURRENT"',
     '  state: "V0_3_7_CANDIDATE1_FROZEN / FRESH_BLIND_PHASE_A_NEXT / NOT_CURRENT / NOT_RELEASED"'),
    ('  event: "V0_3_7_CANDIDATE1_SUCCESSOR_REPAIR_RECONCILED"',
     '  event: "V0_3_7_CANDIDATE1_EXACT_PREFREEZE_PASS_AND_EXTERNAL_FREEZE"'),
    ('  active_candidate_observed_head: "b76bb9e7d0d2ee820d7dcc3a7f72f20fefe363e6"',
     '  active_candidate_observed_head: "ae6903464133cb5bcf3cd8909ecae1215fe0b9ba"'),
    ('  active_candidate_observed_subtree: "25d068d158ee37e4e43481c345cce9281febddd1"',
     '  active_candidate_observed_subtree: "c0458e0d7ea417b841cbf4c8bf6e64e4aff37319"'),
    ('  candidate_state: SUCCESSOR_REPAIR_RECONCILED_EXACT_PREFREEZE_NEXT\n  exact_prefreeze_next: true',
     '  candidate_state: FROZEN_FRESH_BLIND_PHASE_A_NEXT\n  exact_prefreeze_run: 33055811978\n  frozen_source: "ae6903464133cb5bcf3cd8909ecae1215fe0b9ba"\n  frozen_subtree: "c0458e0d7ea417b841cbf4c8bf6e64e4aff37319"\n  freeze_record: "collaboration/reconciliation/2026-08-27-v037-candidate1-freeze.md"\n  postfreeze_independence_decision: FRESH_BLIND_SUCCESSOR_REVIEW_WARRANTED\n  independence_decision_record: "collaboration/reconciliation/2026-08-27-v037-candidate1-post-freeze-independence-decision.md"\n  fresh_phase_a_issue: 128\n  fresh_phase_a_branch: "validation/v037-c1-blind-phase-a-primary"\n  fresh_phase_a_entry: "collaboration/reconciliation/2026-08-27-v037-candidate1-blind-phase-a-entry.md"\n  exact_prefreeze_next: false'),
    ('  current_state: CANDIDATE1_SUCCESSOR_REPAIR_RECONCILED_EXACT_PREFREEZE_NEXT',
     '  current_state: CANDIDATE1_FROZEN_FRESH_BLIND_PHASE_A_NEXT'),
    ('    - candidate-ID collision remains a visible namespace residual because no universal uniqueness contract is established\n  next_required_steps:\n    - "run an exact candidate.1 pre-freeze gate bound to one exact source commit and candidate subtree"\n    - "include Current isolation, inherited candidate checks, sealed-Phase-A successor regressions, and focused open-branch regressions"\n    - "freeze candidate.1 only if the exact-source gate passes; bind source/subtree externally without rewriting tested cargo"\n    - "after freeze, explicitly reconcile whether any additional independent review is warranted; do not silently equate targeted revalidation with fresh Phase A"\n    - "keep attack cardinality open and visible residuals durable; do not convert unknown namespace policy into universal law"\n    - "do not modify or promote releases/current/ during candidate.1 validation/freeze"',
     '    - candidate-ID collision remains a visible namespace residual because no universal uniqueness contract is established\n    - candidate.1 package state reconciled to exact-pre-freeze before binding\n    - exact candidate.1 pre-freeze run 33055811978 PASS on source ae6903464133cb5bcf3cd8909ecae1215fe0b9ba / subtree c0458e0d7ea417b841cbf4c8bf6e64e4aff37319\n    - external freeze record binds the exact tested tree without rewriting candidate cargo\n    - post-freeze independence decision found one fresh blind successor review pays epistemic rent\n    - blind validation branch and Issue 128 prepared without author attack-map priming\n  next_required_steps:\n    - "have a genuinely fresh reviewer inspect only the minimal blind entry and exact frozen candidate.1 bytes"\n    - "seal the Phase-A report on validation/v037-c1-blind-phase-a-primary before opening author-side context"\n    - "project manager independently verifies seal identity and candidate subtree immutability"\n    - "only after the seal, reconcile independent findings against author/repair evidence in Phase B"\n    - "if a material candidate-byte defect is established, create candidate.2 rather than mutate frozen candidate.1"\n    - "keep attack cardinality open and Current v0.3.6 unchanged"'),
    ('  observed_head: "b76bb9e7d0d2ee820d7dcc3a7f72f20fefe363e6"\n  observed_subtree: "25d068d158ee37e4e43481c345cce9281febddd1"\n  state: SUCCESSOR_REPAIR_RECONCILED_EXACT_PREFREEZE_NEXT\n  frozen: false',
     '  observed_head: "ae6903464133cb5bcf3cd8909ecae1215fe0b9ba"\n  observed_subtree: "c0458e0d7ea417b841cbf4c8bf6e64e4aff37319"\n  state: FROZEN_FRESH_BLIND_PHASE_A_NEXT\n  frozen: true\n  frozen_source: "ae6903464133cb5bcf3cd8909ecae1215fe0b9ba"\n  frozen_subtree: "c0458e0d7ea417b841cbf4c8bf6e64e4aff37319"\n  freeze_record: "collaboration/reconciliation/2026-08-27-v037-candidate1-freeze.md"\n  exact_prefreeze_run: 33055811978\n  fresh_phase_a_issue: 128\n  fresh_phase_a_branch: "validation/v037-c1-blind-phase-a-primary"\n  fresh_phase_a_entry: "collaboration/reconciliation/2026-08-27-v037-candidate1-blind-phase-a-entry.md"'),
])

apply("research/plans/PROGRESS.yaml", [
    ('status: V0_3_7_CANDIDATE1_SUCCESSOR_REPAIR_RECONCILED_EXACT_PREFREEZE_NEXT',
     'status: V0_3_7_CANDIDATE1_FROZEN_FRESH_BLIND_PHASE_A_NEXT'),
    ('  state: SUCCESSOR_REPAIR_RECONCILED_EXACT_PREFREEZE_NEXT\n  candidate_branch: candidate/v0.3.7-candidate.1\n  branch_head_is_frozen_identity: false\n  observed_head: b76bb9e7d0d2ee820d7dcc3a7f72f20fefe363e6\n  observed_candidate_subtree: 25d068d158ee37e4e43481c345cce9281febddd1\n  current_subtree_same_head: 7dcbb3934883ffa6cc5292a662588cafc1533cff\n  reconciliation_record: collaboration/reconciliation/2026-08-27-v037-candidate1-successor-repair-reconciliation.md\n  targeted_revalidation_run: 33052764739\n  open_branch_reprobe_run: 33052764661\n  exact_prefreeze_validation: PENDING\n  frozen: false',
     '  state: FROZEN_FRESH_BLIND_PHASE_A_NEXT\n  candidate_branch: candidate/v0.3.7-candidate.1\n  branch_head_is_frozen_identity: false\n  frozen_source_commit: ae6903464133cb5bcf3cd8909ecae1215fe0b9ba\n  frozen_candidate_subtree: c0458e0d7ea417b841cbf4c8bf6e64e4aff37319\n  current_subtree_same_head: 7dcbb3934883ffa6cc5292a662588cafc1533cff\n  reconciliation_record: collaboration/reconciliation/2026-08-27-v037-candidate1-successor-repair-reconciliation.md\n  freeze_record: collaboration/reconciliation/2026-08-27-v037-candidate1-freeze.md\n  independence_decision_record: collaboration/reconciliation/2026-08-27-v037-candidate1-post-freeze-independence-decision.md\n  targeted_revalidation_run: 33052764739\n  open_branch_reprobe_run: 33052764661\n  exact_prefreeze_run: 33055811978\n  exact_prefreeze_validation: PASS\n  fresh_phase_a_issue: 128\n  fresh_phase_a_branch: validation/v037-c1-blind-phase-a-primary\n  fresh_phase_a_entry: collaboration/reconciliation/2026-08-27-v037-candidate1-blind-phase-a-entry.md\n  frozen: true'),
    ('    state: CANDIDATE1_SUCCESSOR_REPAIR_RECONCILED_EXACT_PREFREEZE_NEXT\n    current_candidate_identity: v0.3.7-candidate.1\n    predecessor_frozen_identity: v0.3.7-candidate.0\n    mutable_in_place: true_until_successor_freeze_only\n    exact_prefreeze_validation: PENDING',
     '    state: CANDIDATE1_FROZEN_FRESH_BLIND_PHASE_A_NEXT\n    current_candidate_identity: v0.3.7-candidate.1\n    predecessor_frozen_identity: v0.3.7-candidate.0\n    mutable_in_place: false_frozen_successor_required_for_material_change\n    exact_prefreeze_validation: PASS\n    exact_prefreeze_run: 33055811978'),
    ('    candidate1_additional_independent_review_after_freeze: EXPLICIT_DECISION_PENDING',
     '    candidate1_additional_independent_review_after_freeze: FRESH_BLIND_SUCCESSOR_REVIEW_WARRANTED\n    candidate1_fresh_phase_a_issue: 128\n    candidate1_fresh_phase_a_branch: validation/v037-c1-blind-phase-a-primary\n    candidate1_fresh_phase_a_entry: collaboration/reconciliation/2026-08-27-v037-candidate1-blind-phase-a-entry.md'),
    ('immediate_next_action:\n  id: CANDIDATE1_EXACT_PREFREEZE_VALIDATION\n  target: V0_3_7_CANDIDATE1_EXACT_SOURCE_AND_SUBTREE\n  objective: >-\n    Run the full candidate.1 pre-freeze validation on one exact committed source head,\n    preserving Current isolation and combining inherited candidate gates with all\n    successor repair regressions derived from sealed Phase A and later focused probes.\n  candidate_identity: v0.3.7-candidate.1\n  candidate_branch: candidate/v0.3.7-candidate.1\n  observed_pre_gate_head: b76bb9e7d0d2ee820d7dcc3a7f72f20fefe363e6\n  observed_pre_gate_subtree: 25d068d158ee37e4e43481c345cce9281febddd1\n  predecessor_phase_a_seal: 5ba3d241efa460fe170253860ad67045aa1d96a5\n  current_must_remain: v0.3.6\n  do_not_promote: true\n\nnext_after_exact_prefreeze:\n  - if exact-source validation fails, repair candidate.1 before freeze and rerun the exact gate\n  - if it passes, bind the exact candidate.1 source commit and subtree in an external freeze record without rewriting tested cargo\n  - explicitly decide whether additional independent post-freeze review is warranted; targeted same-falsifier revalidation is not fresh Phase A\n  - reconcile visible residuals without treating every unknown as a release blocker\n  - only after governed acceptance consider release preparation/promotion; Current remains v0.3.6 until then',
     'immediate_next_action:\n  id: CANDIDATE1_FRESH_BLIND_PHASE_A\n  target: V0_3_7_CANDIDATE1_EXACT_FROZEN_TREE\n  objective: >-\n    Obtain one genuinely fresh blind inspection of the exact frozen candidate.1 bytes,\n    growing an independent attack tree before any author-side repair or oracle context\n    is exposed. Persist and seal Phase A before Phase B reconciliation.\n  candidate_identity: v0.3.7-candidate.1\n  frozen_source: ae6903464133cb5bcf3cd8909ecae1215fe0b9ba\n  frozen_subtree: c0458e0d7ea417b841cbf4c8bf6e64e4aff37319\n  validation_branch: validation/v037-c1-blind-phase-a-primary\n  blind_entry: collaboration/reconciliation/2026-08-27-v037-candidate1-blind-phase-a-entry.md\n  issue: 128\n  report_path: collaboration/reconciliation/2026-08-27-v037-candidate1-independent-phase-a-primary.md\n  current_must_remain: v0.3.6\n  do_not_promote: true\n\nnext_after_candidate1_phase_a:\n  - independently verify the Phase-A seal and frozen subtree identity\n  - only then open author-side evidence for Phase B reconciliation\n  - material candidate-byte defect requires candidate.2; do not mutate frozen candidate.1\n  - non-contract residuals remain visible rather than being universalized merely for closure\n  - only after evidence reconciliation consider release preparation/promotion'),
    ('  candidate1_may_mutate_before_freeze: true\n  candidate1_material_change_after_freeze_requires_successor: true',
     '  candidate1_may_mutate_before_freeze: true\n  candidate1_is_now_frozen: true\n  candidate1_may_mutate_now: false\n  candidate1_material_change_after_freeze_requires_successor: true'),
    ('  exact_prefreeze_next: true\n  attack_cardinality: OPEN',
     '  exact_prefreeze_next: false\n  exact_prefreeze_run: 33055811978\n  frozen_source: ae6903464133cb5bcf3cd8909ecae1215fe0b9ba\n  frozen_subtree: c0458e0d7ea417b841cbf4c8bf6e64e4aff37319\n  attack_cardinality: OPEN'),
    ('  - EDIT_FROZEN_CANDIDATE0_IN_PLACE',
     '  - EDIT_FROZEN_CANDIDATE0_IN_PLACE\n  - EDIT_FROZEN_CANDIDATE1_IN_PLACE\n  - PRIME_CANDIDATE1_FRESH_VALIDATOR_WITH_AUTHOR_REPAIR_OR_ATTACK_CONTEXT'),
])

apply("research/handoffs/CURRENT-HANDOFF.yaml", [
    ('schema_version: "2.5"', 'schema_version: "2.6"'),
    ('  phase_a_entry: collaboration/reconciliation/2026-08-27-v037-candidate0-blind-phase-a-entry.md',
     '  phase_a_entry: collaboration/reconciliation/2026-08-27-v037-candidate1-blind-phase-a-entry.md\n  phase_a_target_identity: v0.3.7-candidate.1\n  phase_a_target_source: ae6903464133cb5bcf3cd8909ecae1215fe0b9ba\n  phase_a_target_subtree: c0458e0d7ea417b841cbf4c8bf6e64e4aff37319\n  phase_a_validation_branch: validation/v037-c1-blind-phase-a-primary\n  phase_a_issue: 128'),
    ('  candidate1_observed_head: b76bb9e7d0d2ee820d7dcc3a7f72f20fefe363e6\n  candidate1_observed_subtree: 25d068d158ee37e4e43481c345cce9281febddd1',
     '  candidate1_frozen_source: ae6903464133cb5bcf3cd8909ecae1215fe0b9ba\n  candidate1_frozen_subtree: c0458e0d7ea417b841cbf4c8bf6e64e4aff37319\n  candidate1_current_subtree_at_freeze: 7dcbb3934883ffa6cc5292a662588cafc1533cff'),
    ('  candidate1_final_open_branch_run: 33052764661\n  candidate1_state: SUCCESSOR_REPAIR_RECONCILED_EXACT_PREFREEZE_NEXT\n  immediate_next_action: CANDIDATE1_EXACT_PREFREEZE_VALIDATION\n  current_handoff_record_refresh: REQUIRED_AFTER_NEXT_MATERIAL_GATE',
     '  candidate1_final_open_branch_run: 33052764661\n  candidate1_exact_prefreeze_run: 33055811978\n  candidate1_freeze_record: collaboration/reconciliation/2026-08-27-v037-candidate1-freeze.md\n  candidate1_independence_decision: FRESH_BLIND_SUCCESSOR_REVIEW_WARRANTED\n  candidate1_independence_decision_record: collaboration/reconciliation/2026-08-27-v037-candidate1-post-freeze-independence-decision.md\n  candidate1_fresh_phase_a_issue: 128\n  candidate1_state: FROZEN_FRESH_BLIND_PHASE_A_NEXT\n  immediate_next_action: CANDIDATE1_FRESH_BLIND_PHASE_A\n  current_handoff_record_refresh: REQUIRED_NOW_AFTER_FREEZE_MATERIAL_GATE'),
    ('  successor_frozen: false\n  successor_current: false\n  exact_prefreeze_validation: PENDING',
     '  successor_frozen: true\n  successor_current: false\n  frozen_source: ae6903464133cb5bcf3cd8909ecae1215fe0b9ba\n  frozen_subtree: c0458e0d7ea417b841cbf4c8bf6e64e4aff37319\n  exact_prefreeze_validation: PASS\n  exact_prefreeze_run: 33055811978\n  fresh_blind_phase_a_next: true\n  fresh_blind_phase_a_issue: 128'),
    ('    - validation/v037-c0-blind-phase-a-primary\n  validation_branch_role: SEALED_PHASE_A_OCCURRENCE_TRUTH\n  candidate0_branch_role: FROZEN_PREDECESSOR_LINEAGE\n  candidate1_branch_role: ACTIVE_SUCCESSOR_PREFREEZE_WORKSPACE',
     '    - validation/v037-c0-blind-phase-a-primary\n    - validation/v037-c1-blind-phase-a-primary\n  candidate0_validation_branch_role: SEALED_PREDECESSOR_PHASE_A_OCCURRENCE_TRUTH\n  candidate1_validation_branch_role: FRESH_PHASE_A_INTAKE_PREPARED_NOT_YET_SEALED\n  candidate0_branch_role: FROZEN_PREDECESSOR_LINEAGE\n  candidate1_branch_role: FROZEN_SUCCESSOR_OCCURRENCE_TRUTH'),
])

print("V037_CANDIDATE1_POSTFREEZE_CONTROL_PLANE_READY")
